# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Clean checkout
- checkout: self
  clean: true

# Install Node.js 20
- task: UseNode@1
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Install and build (if project is in subfolder, add cd web)
- script: |
    rm -rf node_modules
    npm install
    npm run build
  displayName: 'npm install and build'

